version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
  js:
    build: docker/js
    command: npm start
    working_dir: /codebase
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/codebase
